<?php
/**
 * Paybox Epayment module for Magento
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * available at : http://opensource.org/licenses/osl-3.0.php
 *
 * @package    Paybox_Epayment
 * @copyright  Copyright (c) 2013-2014 Paybox
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * @see Mage_Payment_Block_Info
 */
$method = $this->getMethod();
$info = $this->getInfo();
$data = $this->getPayboxData();
$debitType = $this->getDebitTypeLabel();
$threeTime = $this->getThreeTimeLabels();
?>
<p><strong><?php echo $this->htmlEscape($method->getTitle()); ?></strong></p>
<?php if ($this->isAuthorized() && $this->getShowInfoToCustomer()): ?>
<table><tbody>
    <tr>
        <th><?php echo $this->__('Payment method'); ?></th>
    </tr>
    <tr>
        <td><img alt="<?php echo $this->escapeHtml($this->getCardImageLabel()); ?>" src="<?php echo $this->escapeHtml($this->getCardImageUrl()); ?>"/></td>
    </tr>
<?php if (isset($data['ip'])): ?>
    <tr>
        <th><?php echo $this->__('Country of IP'); ?></th>
    </tr>
    <tr>
        <td><?php echo $this->escapeHtml($data['ip']); ?></td>
    </tr>
<?php endif; ?>
    <tr>
        <th><?php echo $this->__('Processing date'); ?></th>
    </tr>
    <tr>
        <td><?php echo $this->escapeHtml(preg_replace('/^([0-9]{2})([0-9]{2})([0-9]{4})$/', '$1/$2/$3', $data['date'])); ?></td>
    </tr>
<?php if (!is_null($debitType)): ?>
    <tr>
        <th><?php echo $this->__('Debit type'); ?></th>
    </tr>
    <tr>
        <td><?php echo $this->escapeHtml($debitType); ?></td>
    </tr>
<?php endif; ?>
<?php if (!is_null($threeTime)): ?>
    <tr>
        <th><?php echo $this->__('First debit'); ?></th>
    </tr>
    <tr>
        <td><?php echo $this->escapeHtml($threeTime['first']); ?></td>
    </tr>
    <tr>
        <th><?php echo $this->__('Second debit'); ?></th>
    </tr>
    <tr>
        <td><?php echo $this->escapeHtml($threeTime['second']); ?></td>
    </tr>
    <tr>
        <th><?php echo $this->__('Third debit'); ?></th>
    </tr>
    <tr>
        <td><?php echo $this->escapeHtml($threeTime['third']); ?></td>
    </tr>
<?php endif; ?>
<?php if (isset($data['country'])): ?>
    <tr>
        <th><?php echo $this->__('Card country'); ?></th>
    </tr>
    <tr>
        <td><?php echo $this->escapeHtml($data['country']); ?></td>
    </tr>
<?php endif; ?>
<?php if (isset($data['firstNumbers']) && isset($data['lastNumbers'])): ?>
    <tr>
        <th><?php echo $this->__('Card numbers'); ?></th>
    </tr>
    <tr>
        <td><?php echo $this->escapeHtml($data['firstNumbers'].'...'.$data['lastNumbers']); ?></td>
    </tr>
<?php endif; ?>
<?php if (isset($data['validity'])): ?>
    <tr>
        <th><?php echo $this->__('Validity date'); ?></th>
    </tr>
    <tr>
        <td><?php echo $this->escapeHtml(preg_replace('/^([0-9]{2})([0-9]{2})$/', '$2/$1', $data['validity'])); ?></td>
    </tr>
<?php endif; ?>
</tbody></table>
<?php endif; ?>
<?php echo $this->getChildHtml()?>
